services:

  keycloak-db:
    image: postgres:latest
    command: postgres -c "max_connections=200"
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  vitalis_db:
    image: postgres:latest
    container_name: vitalis_db
    environment:
      POSTGRES_DB: vitalis
      POSTGRES_USER: vitalis
      POSTGRES_PASSWORD: vitalis
    volumes:
      - vitalis_db_data:/var/lib/postgresql/data
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vitalis"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      jgroups.dns.query: keycloak
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEME: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "80:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - shared_network

  vitalis:
    image: ghcr.io/ne-se-chete/vitalis:latest
    container_name: vitalis
    environment:
      DIRIGIBLE_MULTI_TENANT_MODE: "false"
      SPRING_PROFILES_ACTIVE: keycloak
      DIRIGIBLE_KEYCLOAK_AUTH_SERVER_URL: https://keycloak/realms/ne-se-chete
      DIRIGIBLE_KEYCLOAK_CLIENT_ID: vitalis
      DIRIGIBLE_KEYCLOAK_CLIENT_SECRET: ${BACKEND_CLIENT_SECRET}
      DIRIGIBLE_TRIAL_ENABLED: "true"
      DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES: PostgreSQL
      PostgreSQL_DRIVER: org.postgresql.Driver
      PostgreSQL_URL: jdbc:postgresql://vitalis_db:5432/vitalis
      PostgreSQL_USERNAME: vitalis
      PostgreSQL_PASSWORD: vitalis
      DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT: PostgreSQL
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    networks:
      - shared_network

volumes:
  keycloak_db_data:
    driver: local
  vitalis_db_data:
    driver: local

networks:
  shared_network:
    driver: bridge
