name: Deploy - Vitalis

on:
  workflow_run:
    workflows: Build - Vitalis
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/latest/download/kompose-linux-amd64 -o /usr/local/bin/kompose
          chmod +x /usr/local/bin/kompose

      - name: Convert Docker Compose to Kubernetes Manifests
        run: |
          mkdir -p k8s-manifests
          kompose convert -f deployment/docker-compose.yaml -o k8s-manifests/

      - name: Authenticate with Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-manifests/
